name: Python and Multiline Script Workflow
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  run_python:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
 
    - name: Run Python script
      run: python test.py
 
  run_multiline_script:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Run multiline script
      run: |
        echo "This is a multiline script."
        echo "It can have multiple lines of commands."
        echo "You can execute any command here."
        echo $purpose

      env:
        purpose: "for testing"